### ISSUE TITLE
怎么不能定制width

### ISSUE THREAD

**Issue by hihl** [hustcc/echarts-for-react#1]

**Comment by hustcc** [comment]
width可以自己在外面包裹一下来定制，例如：
```js
<div className="chart_wrapper">
    <ReactEcharts
        option={this.getOtion()} 
        height={300} />
</div>
```
然后设置css：
```css
.chart_wrapper {
 width: 60%;
}
```
