### ISSUE TITLE
移动端显示异常

### ISSUE THREAD

**Issue by hanxiansen** [hustcc/echarts-for-react#87]
移动端的话文字显示都很小，强制调大也异常，问下有什么解决方案不？

**Comment by deot** [comment]
希望可以帮到你，我之前项目处理的方法[点我link](https://github.com/deot/react-examples/tree/master/08-react-basic-02/common/js/components/CreateEcharts)，不过你还要给涉及到大小的样式进行配对，我的方式是采用给`body`增加一个`g-init-echart`的类, 可能还需要改其他类，下面可以参考下
```css
@mixin formatResize($scale) {
  line-height: 40px / $scale !important;
  font-size: 26px / $scale !important;
}
body{
  @include formatResize(1);
}
body.g-init-echart {
  @include formatResize(2);
}
```
